[workspace]
members = [".", "derive"]

[package]
name = "envir"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"
license = "MIT"
description = "Deserialize/serialize struct from/to env"
repository = "https://github.com/sanpii/envir"

[dependencies.dotenvy]
version = "0.15"
optional = true

[dependencies.envir_derive]
version = "0.1"
path = "derive/"
optional = true

[dependencies.regex]
version = "1.0"
optional = true

[features]
default = ["dotenv"]
dotenv = ["dotenvy"]
extrapolation = ["regex", "serde"]
serde = ["envir_derive"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
