[workspace]
members = [".", "derive"]

[package]
name = "envir"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"
license = "MIT"
description = "Deserialize/serialize struct from/to env"
repository = "https://github.com/sanpii/envir"

[dependencies.envir_derive]
version = "0.1"
path = "derive/"

[dependencies.regex]
version = "1.0"
optional = true

[features]
extrapolation = ["regex"]
